const canciones = [

    { nombre: `Los Aldeanos - A Veces`, url: 'https://youtu.be/kVdzzHhyND4' },
    { nombre: 'Sebastián Yatra, Reik - Un Año', url: 'https://youtu.be/9Hz2thX2b7E' },
    { nombre: 'Sebastián Yatra - No hay nadie más', url:  'https://youtu.be/e_nBNkGwcQs' },
    { nombre: 'Matisse, Reik - Eres Tú', url:  'https://youtu.be/TW2YDZ-NpUE' },
    { nombre: 'Saint Motel - Cold Cold Man', url: 'https://youtu.be/TOOr1HfrjsA' },
    { nombre: 'The Lumineers - Sleep On The Floor', url: 'https://youtu.be/IE2NjdNUGME' },
    { nombre: 'Madcon - Beggi', url: 'https://youtu.be/WNYYvHfLCG0' },
    { nombre: 'Coldplay - Adventure Of A Lifetime ', url: 'https://youtu.be/3kN4uVaIQSM' },
    { nombre: 'Creedence Clearwater Revival - Have you ever seen the Rain?', url: 'https://youtu.be/gm1P3zLmLVg' },
    { nombre: 'PUBLIC - Make You Mine', url: 'https://youtu.be/oAHWySVCDjk' },
    { nombre: 'Wallows - Are You Bored Yet?', url: 'https://youtu.be/mh96bLWRupU' },
    { nombre: 'Twenty one pilots - Hometown', url: 'https://youtu.be/AUuXOftmFHg' },
    { nombre: 'León Larregui - Como Tú', url: 'https://youtu.be/P1-891_aOKY' },
    { nombre: 'Bruno Mars - Locked Out Of Heaven', url: 'https://youtu.be/XbJxN6No6Y8' },
    { nombre: 'Transparente', url: 'https://youtu.be/BNzKY9bNM7M' },
    { nombre: 'Caztro - Ese No Sé Qué', url: 'https://youtu.be/FQ6OsHvMwbw' },
    { nombre: 'Inspector- Me Estoy Enamorando', url: 'https://youtu.be/sWuBeQ0uvaw' },
    { nombre: 'Concorde - Just Kiss Her', url: 'https://youtu.be/U5YMu3rzXcI' },
    { nombre: 'Twenty One Pilots - Polarize', url: 'https://youtu.be/53NKcZGisCA' },
    { nombre: 'EL ÚLTIMO ROMÁNTICO - Brock Ansiolitiko', url: 'https://youtu.be/8Zh1vHTzxLk' },
    { nombre: 'Twenty One Pilots - Tear In My Heart', url: 'https://youtu.be/AIrEgxjgqps' },
    { nombre: 'Hombres G- Si yo no te tengo a ti', url: 'https://youtu.be/vqcjoseWAi4' },
    { nombre: 'Elvin Bishop - Fooled around and fell in love', url: 'https://youtu.be/ZY2zB--uo1s' },
    { nombre: 'Nicky Romero & Stadiumx - Love You Forever', url: 'https://youtu.be/2283IXqP3S0' },
    { nombre: 'Dimitri Vegas, MOGUAI & Like Mike - Body Talk', url: 'https://youtu.be/eaAborEFPfw' },
    { nombre: 'Sigala ft. John Newman, Nile Rodgers - Give Me Your Love', url: 'https://youtu.be/5N_xlkM8pFY' },
    { nombre: 'Sam feldt & Dante klein feat. Milo - Feels like home', url: 'https://youtu.be/N-v3UmsLyGU' },
    { nombre: 'Sam Feldt & The Him featuring The Donnies The Amys - Drive You Home', url: 'https://youtu.be/iXo_9fHDQGA' },
    { nombre: 'Tompkins Square Park - Mumford And Sons', url: 'https://youtu.be/tfBVDHT2l0w' },
    { nombre: 'Oliver Tree - All I got', url: 'https://youtu.be/dyyAFhDrptM' },
    { nombre: 'Sadeyes - You deserve better', url: 'https://youtu.be/jCtpx9c0Cps' },
    { nombre: 'Katie Sky | Monsters', url: 'https://youtu.be/nWcfv-_iE-4' },
    { nombre: 'ARROWS - FENCES ft. Macklemore & Ryan Lewis', url: 'https://youtu.be/sMa6bJOr8r8' },
    { nombre: 'Flash Theme', url: 'https://youtu.be/OqrsduS3eIo' },
    { nombre: 'Calvin Harris - I Need Your Love ', url: 'https://youtu.be/AtKZKl7Bgu0' },
    { nombre: 'Lilly Wood & The Prick and Robin Schulz - Prayer In C', url: 'https://youtu.be/fiore9Z5iUg' },
    { nombre: 'Nicky Romero - Take Me (ft. Colton Avery)', url: 'https://youtu.be/rTh3g3MLawY' },
    { nombre: 'Leo Dan - Como Te Extraño Amor', url: 'https://youtu.be/kFf0E_b33_U' },
    { nombre: 'You and I - Barns Courtney', url: 'https://youtu.be/y2Z-OtYObtg' },
    { nombre: 'Calvin Harris feat. Example - We will Be Coming Back', url: 'https://youtu.be/j_9oW6ZNjEw' },
    { nombre: 'The Fray - Look After You', url: 'https://youtu.be/HKBNJHmJ1K0' },
    { nombre: 'AWAY - William', url: 'https://youtu.be/bQWhW4UEAxY' },
    { nombre: 'Twenty one pilots - Lovely', url: 'https://youtu.be/-C2JRWI43nA' },
    { nombre: 'Broken - Lovelytheband', url: 'https://youtu.be/Z7a_wj4pZK0' },
    { nombre: 'Lost Frequencies feat. Janieck Devy - Reality', url: 'https://youtu.be/ilw-qmqZ5zY' },
    { nombre: 'Michael Calfan - Nobody Does It Better', url: 'https://youtu.be/vMbfFv3yv5s' },
    { nombre: 'Beret - Si por mi fuera', url: 'https://youtu.be/NvTvBUJXIvg' },
    { nombre: 'Manuel Medrano - Bajo El Agua', url: 'https://youtu.be/NvTvBUJXIvg' },
    { nombre: 'VIDEOCLUB - Amour Plastique', url: 'https://youtu.be/PiSfroMnqWA' },
    { nombre: 'VIDEOCLUB – En nuit', url: 'https://youtu.be/hCHlnHp3YaM' },
    { nombre: 'VIDEOCLUB - Roi', url: 'https://youtu.be/vh0dcNxaNtI' },
    { nombre: 'Arctic Monkeys - Fluorescent Adolescent', url: 'https://youtu.be/mF51vApw5lc' },
    { nombre: 'Dayglow - Can I Call You Tonight? ', url: 'https://youtu.be/RCU9aK3sB40' },
    { nombre: `Earth, Wind & Fire - Let's Groove`, url: 'https://youtu.be/cdV-DheAXgc' },
    { nombre: 'MGMT - Kids', url: 'https://youtu.be/Svnxrfq8ksA' },
    { nombre: `KISS- I Was Made For Lovin' You`, url: 'https://youtu.be/fqy5hQH89KM' },
    { nombre: 'Imagine Dragons - Walking The Wire', url: 'https://youtu.be/0ZYsqPMsybQ' },
    { nombre: 'Imagine Dragons - Birds', url: 'https://youtu.be/1aRZYHUtsaE' },
    { nombre: 'Imagine Dragons - West Coast', url: 'https://youtu.be/_ldMl6hw4aw' },
    { nombre: 'Larger Than Life Pinkzebra ft. Benji Jackson', url: 'https://youtu.be/po7IRr8xZig' },
    { nombre: 'Foster The People - Waste', url: 'https://youtu.be/BWoMTWz0TzQ' },
    { nombre: 'Vance Joy - Riptide', url: 'https://youtu.be/GW8AS2X5FSQ' },
    { nombre: 'The Lumineers - Ho Hey', url: 'https://youtu.be/aDhtdn3dnOc' },
    { nombre: 'Walking On A Dream - Empire Of The Sun', url: 'https://youtu.be/oXIejXE4-fY' },
    { nombre: 'The Best - Awolnation feat. Alice Merton', url: 'https://youtu.be/dRmkjvTY4Kg' },
    { nombre: 'Coldplay - Hymn For The Weekend', url: 'https://youtu.be/9waxrnkYCMc' },
    { nombre: 'The Night Out - Martin Solveig', url: 'https://youtu.be/lV8pForfjiM' },
    { nombre: 'Foster The People - Best Friend', url: 'https://youtu.be/nyHwlbOU5yE' },
    { nombre: 'Kevin Kaarl - Vámonos a Marte', url: 'https://youtu.be/DxUJPrSrTRk' },
    { nombre: 'Gorillaz - On Melancholy Hill', url: 'https://youtu.be/zIo2n4NN_zU' },
    { nombre: 'Porta - Amor', url: 'https://youtu.be/iDaU73ROops' },
    { nombre: 'Rafa Espino - Andrómeda', url: 'https://youtu.be/JzrxGICE-Vw' },
    { nombre: 'Los Bunkers - Bailando Solo', url: 'https://youtu.be/E3BjONhtBa0' },
    { nombre: 'Phillip Phillips - Gone, Gone, Gone', url: 'https://youtu.be/cH7rKup3HF0' },
    { nombre: 'Passion Pit - Carried Away', url: 'https://youtu.be/jbD6HC3ZU2w' },
    { nombre: 'Toploader - Dancing in the moonlight', url: 'https://youtu.be/a8s_2waEy9A' },
    { nombre: 'Eagle eye cherry - Save tonight', url: 'https://youtu.be/J2FEb1ZG2-0' },
    { nombre: 'Jaymes young - What is love', url: 'https://youtu.be/UxDdPf6CDVY' },
    { nombre: 'Rick Astley - Never Gonna Give You Up', url: 'https://youtu.be/dh5UfkDyQts' },
    { nombre: 'Coldplay - Yellow', url: 'https://youtu.be/6AStdL1OXSA' },
    { nombre: 'Coldplay - The scientist', url: 'https://youtu.be/4aeFHCbO_sM' },
    { nombre: `Arctic Monkeys - Baby I'm Yours`, url: 'https://youtu.be/VSCOvHsPCxY' },
    { nombre: `Twenty one pilots - Smithereens`, url: 'https://youtu.be/lcpVMHd9LXk' },
    { nombre: `Little Jesus - La Magia`, url: 'https://youtu.be/fuV1Md2haQg' },
    { nombre: `Benny Benassi - Cinema`, url: 'https://youtu.be/6KeQjz3ZlDc' },
    { nombre: `Los surfistas del sistema - La magia está en tu piel`, url: 'https://youtu.be/1aTZ_5H5XQo' },
    { nombre: `Arctic monkeys - Mardy bum`, url: 'https://youtu.be/E0femeBbCOg' },
    { nombre: `The Neighbourhood - Compass`, url: 'https://youtu.be/HBCmeMQbYfE' },
    { nombre: `Here Comes The Sun - The Beatles `, url: 'https://youtu.be/1K6xyB2-xAk' },
    { nombre: `Muzzaik & Stadiumx - So Much Love`, url: 'https://youtu.be/n8m0bRFIBlI' },
    { nombre: `Firebeatz & Apster ft. Spree Wilson - Ghostchild`, url: 'https://youtu.be/xJ_jIm6HhP4' },
    { nombre: `Two Friends ft. Kevin Writer - While We’re Dreaming`, url: 'https://youtu.be/Uzn_WYBXtv8' },
    { nombre: `Diego Verdaguer — La Ladrona`, url: 'https://youtu.be/DsZRso83VZQ' },
    { nombre: `The Police - Every Breath You Take`, url: 'https://youtu.be/6afav_M2w7w' },
    { nombre: `Imagine Dragons - Only`, url: 'https://youtu.be/Ad3St7UJ9p0' },
    { nombre: `Ed Maverick - Quiero`, url: 'https://youtu.be/AWTKgnlw4Ro' },
    { nombre: `Counting Crows- Accidentally in love`, url: 'https://youtu.be/632fGN0oNGI' },
    { nombre: `Jósean Log - Chachachá`, url: 'https://youtu.be/QVxzkhgSjXc' },
    { nombre: `Do you Feel It? - Chaos Chaos`, url: 'https://youtu.be/MebcE5dQdQE' },
    { nombre: `Kygo - Never Let You Go`, url: 'https://youtu.be/9GJS1KKQWJk' },
    { nombre: `Jaymes Young - Feel Something`, url: 'https://youtu.be/q5gQtyobFLg' },
    { nombre: `Hombres G - Te quiero`, url: 'https://youtu.be/50IiDnZRGzQ' },
    { nombre: `Soda stereo - Música ligera`, url: 'https://youtu.be/kNTjC9sQvfg' },
    { nombre: `Tipling Rock - Staring`, url: 'https://youtu.be/EN-rjBmpJkw' },
    { nombre: `Tony True And The Tijuana Tres - Me Gustas`, url: 'https://youtu.be/G8sCgFOElSU' },
    { nombre: `León Larregui - Locos`, url: 'https://youtu.be/difAEKi9wjw' },
    { nombre: `Roy orbison - Oh, Pretty Woman`, url: 'https://youtu.be/tfDOSHtj4RE' },
    { nombre: `Dame Una Señal - Roberto Jordan`, url: 'https://youtu.be/1yVMYQQlWAQ' },
    { nombre: `Enrique Iglesias - Alguien soy yo`, url: 'https://youtu.be/fCULkRCAJxo' },
    { nombre: `Enrique Iglesias - Ayer`, url: 'https://youtu.be/0L1tKljPk8Q' },
    { nombre: `Enrique Iglesias Ft. Wisin & Yandel - No Me Digas Que No`, url: 'https://youtu.be/H0voOSUkJNo' },
    { nombre: `Avicii - You Make Me`, url: 'https://youtu.be/n_ogAXBNQD4' },
    { nombre: `Haddaway - What Is Love`, url: 'https://youtu.be/km4tYCJfeQE' },
    { nombre: `a-ha - Take On Me`, url: 'https://youtu.be/oYYPQxlr7yM' },
    { nombre: `Jaymes Young - Habits of my Heart`, url: 'https://youtu.be/VZjDkaC0LU4' },
    { nombre: `Morat - Mi Nuevo Vicio`, url: 'https://youtu.be/nYki6HKjX2M' },
    { nombre: `Morat - Besos en guerra`, url: 'https://youtu.be/2lk_Kz_kb8E' },
    { nombre: `The beatles - Love me do`, url: 'https://youtu.be/qVNVKifC-dc' },
    { nombre: `The beatles - She Love You`, url: 'https://youtu.be/hPXDEMtSUcU' },
    { nombre: `Rufus wainwright - Hallelujah`, url: 'https://youtu.be/QLfghYme_Ns' },
    { nombre: `Gerard Way & Ray Toro - Happy Together`, url: 'https://youtu.be/ZHNyH-J7P7E' },
    { nombre: `Grant gustin - Runnin' home to you`, url: 'https://youtu.be/WePPu7C6tT8' },
]

export {
    canciones
}